name: ggclassroom
description: "A cross-platform E-Learning application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  mongo_dart: ^0.10.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  csv: ^5.1.1
  crypto: ^3.0.5
  file_picker: ^8.1.2
  http: ^1.2.1
  fl_chart: ^0.69.0
  mailer: ^6.0.1
  json_annotation: ^4.8.1 
  permission_handler: ^11.0.1 
  image_gallery_saver_plus: ^4.0.1
  device_info_plus: ^10.1.2
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  image: ^4.5.4
  flutter_markdown: ^0.7.7+1
  google_generative_ai: ^0.4.7
  syncfusion_flutter_pdf: ^31.2.16
  desktop_drop: ^0.4.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  json_serializable: ^6.7.1 
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1A73E8"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#1A73E8"
  image: "assets/icons/icon.png"
  android: true
  ios: true
  android_12:
    color: "#1A73E8"
    image: "assets/icons/icon.png"
