name: ggclassroom
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  mongo_dart: ^0.10.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  csv: ^5.1.1
  crypto: ^3.0.5
  file_picker: ^8.1.2
  http: ^1.2.1
  fl_chart: ^0.69.0
  mailer: ^6.0.1
  json_annotation: ^4.8.1 
  permission_handler: ^11.0.1 
  image_gallery_saver_plus: ^4.0.1
  device_info_plus: ^10.1.2
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  json_serializable: ^6.7.1 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
